name: tests

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Modules
        run: npm i

      - name: Prettier/ESlint Action
        run: npm run lint

      - name: Run Jest
        run: npm run test:coverage

      - uses: codecov/codecov-action@v1

      - uses: codfish/semantic-release-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
